### ISSUE TITLE
 Can I book multiple room types?

### ISSUE THREAD

**Issue by datdo06** [WailanTirajoh/Laravel-Hotel#19]
Currently I can only book 1 room for the number of people I fill

**Comment by WailanTirajoh** [comment]
well, it can be implemented. so you want to select multiple room by 1 people?

**Comment by datdo06** [comment]
Currently the customer order automation flow is not found   Sent from Mail for Windows From: Wailan TirajohSent: Saturday, October 7, 2023 7:18 PMTo: WailanTirajoh/Laravel-HotelCc: datdo06; AuthorSubject: Re: [WailanTirajoh/Laravel-Hotel] Can I book multiple room types? (Issue #19) well, it can be implemented. so you want to select multiple room by 1 people?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
