### ISSUE TITLE
Filter (Type)

### ISSUE THREAD

**Issue by datdo06** [WailanTirajoh/Laravel-Hotel#21]
You can create a separate filter in laravel for room types that don't exist, without using a data table

**Comment by WailanTirajoh** [comment]
Can you provide more information about what you want to achieve?

**Comment by datdo06** [comment]
Can you create a search section just for the name

**Comment by datdo06** [comment]
![395311675_352026277190358_3207237613375301191_n](https://github.com/WailanTirajoh/Laravel-Hotel/assets/116553653/47ab77c9-d2ed-477d-a9c2-90863e224aff)

**Comment by WailanTirajoh** [comment]
![image](https://github.com/WailanTirajoh/Laravel-Hotel/assets/53980548/1f0d7c6f-a1b3-486a-9f55-d347a1575520)

@datdo06

**Comment by datdo06** [comment]
thank you
