### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by oscarcuenca** [WailanTirajoh/Laravel-Hotel#3]
Hi.
I am traying to install your repository in my localhost using xampp and i am geting problems when it is being to created the tables : 

 PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")

 C:\xampp\htdocs\Laravel-Hotel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:545
      PDOStatement::execute()

It owuld be possible for you to send me a database sample *.sql to test your application?
Thanks in advance for your help-
Best Regards
Óscar

**Comment by aanachad** [comment]
Just add the line below in the boot function located in /app/Providers/AppServiceProvider.php file.

`Schema::defaultStringLength(191);`

Dont forget the use statement

`use Illuminate\Support\Facades\Schema;`

The file must look like : 

```php
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */public function boot()
    Schema::defaultStringLength(191);
}
`

Tell me what you think about the app, I'm also curious about it.

**Comment by oscarcuenca** [comment]
Hi.
Thanks for your fast reply.
I have not yet launched it since i had that issue. Today i will try to launch it up in my local and i will give you my observations.

If it is all correct maybe you are interested in offering your application to our customers. If so, after making some adaptations we could find a commercial agreetment in order to sell some services aorund your Hotels app-laravel. but first i need to check it all.

Best Regards
óscar

________________________________
De: aanachad ***@***.***>
Enviado: martes, 15 de noviembre de 2022 17:51
Para: WailanTirajoh/Laravel-Hotel ***@***.***>
Cc: Oscar Cuenca Roca ***@***.***>; Author ***@***.***>
Asunto: Re: [WailanTirajoh/Laravel-Hotel] Database connection (Issue #3)


Just add the line below in the boot function located in /app/Providers/AppServiceProvider.php file.

Schema::defaultStringLength(191);

Dont forget the use statement

use Illuminate\Support\Facades\Schema;

The file must look like :

use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */public function boot()
    Schema::defaultStringLength(191);
}
`

Tell me what you think about the app, I'm also curious about it.

**Comment by oscarcuenca** [comment]
Finally I got up server but this issue came:
https://flareapp.io/share/qm1NyVzP#F68

**Comment by WailanTirajoh** [comment]
Hi @oscarcuenca , try to run `npm install && npm run` dev for local development to generate the mix css & js.

**Comment by WailanTirajoh** [comment]
It owuld be possible for you to send me a database sample *.sql to test your application?

you can generate the sql by run `php artisan migrate --seed` on your command line.

**Comment by oscarcuenca** [comment]
Hi Willian
Attached file log for error of mysql.


  1.

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\xampp\phpMyAdmin\libraries\classes\DatabaseInterface.php on line 578

  1.

Also got error while  Compiling Mix
WARNING in .***@***.***/core/lib/index.js 4:0-102
export 'detectOverflow' (reexported as 'detectOverflow') was not found in './createPopper.js' (possible exports: createPopper, popperGenerator)

WARNING in .***@***.***/core/lib/popper-lite.js 11:0-75
export 'detectOverflow' (reexported as 'detectOverflow') was not found in './createPopper.js' (possible exports: createPopper, popperGenerator)

WARNING in .***@***.***/core/lib/popper.js 16:0-75
export 'detectOverflow' (reexported as 'detectOverflow') was not found in './createPopper.js' (possible exports: createPopper, popperGenerator)

ERROR in .***@***.***/core/lib/createPopper.js 1:0-63
Module not found: Error: Can't resolve './dom-utils/getCompositeRect.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 2:0-57
Module not found: Error: Can't resolve './dom-utils/getLayoutRect.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 3:0-65
Module not found: Error: Can't resolve './dom-utils/listScrollParents.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 4:0-61
Module not found: Error: Can't resolve './dom-utils/getOffsetParent.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 5:0-63
Module not found: Error: Can't resolve './dom-utils/getComputedStyle.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 6:0-55
Module not found: Error: Can't resolve './utils/orderModifiers.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 7:0-43
Module not found: Error: Can't resolve './utils/debounce.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 8:0-61
Module not found: Error: Can't resolve './utils/validateModifiers.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 9:0-43
Module not found: Error: Can't resolve './utils/uniqueBy.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 10:0-59
Module not found: Error: Can't resolve './utils/getBasePlacement.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 11:0-49
Module not found: Error: Can't resolve './utils/mergeByName.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 12:0-55
Module not found: Error: Can't resolve './utils/detectOverflow.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/createPopper.js 13:0-54
Module not found: Error: Can't resolve './dom-utils/instanceOf.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/index.js 2:0-37
Module not found: Error: Can't resolve './modifiers/index.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper-lite.js 2:0-59
Module not found: Error: Can't resolve './modifiers/eventListeners.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper-lite.js 3:0-57
Module not found: Error: Can't resolve './modifiers/popperOffsets.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper-lite.js 4:0-57
Module not found: Error: Can't resolve './modifiers/computeStyles.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper-lite.js 5:0-53
Module not found: Error: Can't resolve './modifiers/applyStyles.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 2:0-59
Module not found: Error: Can't resolve './modifiers/eventListeners.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 3:0-57
Module not found: Error: Can't resolve './modifiers/popperOffsets.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 4:0-57
Module not found: Error: Can't resolve './modifiers/computeStyles.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 5:0-53
Module not found: Error: Can't resolve './modifiers/applyStyles.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 6:0-43
Module not found: Error: Can't resolve './modifiers/offset.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 7:0-39
Module not found: Error: Can't resolve './modifiers/flip.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 8:0-61
Module not found: Error: Can't resolve './modifiers/preventOverflow.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 9:0-41
Module not found: Error: Can't resolve './modifiers/arrow.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 10:0-39
Module not found: Error: Can't resolve './modifiers/hide.js' in ***@***.***\core\lib'

ERROR in .***@***.***/core/lib/popper.js 20:0-37
Module not found: Error: Can't resolve './modifiers/index.js' in ***@***.***\core\lib'

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
11 │ @import "~toastr/toastr";
   │         ^^^^^^^^^^^^^^^^
   ╵
  resources\sass\app.scss 11:9  root stylesheet
    at processResult (C:\xampp\htdocs\Laravel-Hotel\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\xampp\htdocs\Laravel-Hotel\node_modules\webpack\lib\NormalModule.js:860:5
    at C:\xampp\htdocs\Laravel-Hotel\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\xampp\htdocs\Laravel-Hotel\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\xampp\htdocs\Laravel-Hotel\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\xampp\htdocs\Laravel-Hotel\node_modules\sass-loader\dist\index.js:54:7
    at Function.call$2 (C:\xampp\htdocs\Laravel-Hotel\node_modules\sass\sass.dart.js:101257:16)
    at render_closure1.call$2 (C:\xampp\htdocs\Laravel-Hotel\node_modules\sass\sass.dart.js:86329:12)
    at _RootZone.runBinary$3$3 (C:\xampp\htdocs\Laravel-Hotel\node_modules\sass\sass.dart.js:30053:18)
    at _FutureListener.handleError$1 (C:\xampp\htdocs\Laravel-Hotel\node_modules\sass\sass.dart.js:28582:21)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 30 errors and 3 warnings


________________________________
De: Wailan Tirajoh ***@***.***>
Enviado: martes, 15 de noviembre de 2022 22:00
Para: WailanTirajoh/Laravel-Hotel ***@***.***>
Cc: Oscar Cuenca Roca ***@***.***>; Mention ***@***.***>
Asunto: Re: [WailanTirajoh/Laravel-Hotel] Database connection (Issue #3)


It owuld be possible for you to send me a database sample *.sql to test your application?

you can generate the sql by run php artisan migrate --seed on your command line.

**Comment by WailanTirajoh** [comment]
may i know about your version of nodejs, php, mysql?

**Comment by aanachad** [comment]
Hi Oscar,
I'm not the repos'owner but I try to help as I can,
As I'm working in a similare project - but large scale - for our customer, I was curious about the effectiveness of this repos but I dont have the chance to test it.

**Comment by oscarcuenca** [comment]
Hi Waian
Nodejs: v18.12.0
PHP 8.0.2
composer: version 2.4.4
xampp: xampp-windows-x64-8.0.2-0-VS16
________________________________
De: Wailan Tirajoh ***@***.***>
Enviado: martes, 15 de noviembre de 2022 22:22
Para: WailanTirajoh/Laravel-Hotel ***@***.***>
Cc: Oscar Cuenca Roca ***@***.***>; Mention ***@***.***>
Asunto: Re: [WailanTirajoh/Laravel-Hotel] Database connection (Issue #3)


may i know about your version of nodejs, php, mysql?

**Comment by aanachad** [comment]
I just installed the repos and it works,
check if you run every command mentionned in readme section, you need also to check your nodejs version.
You can install nvm to switch across multiple versions of npm.
For me I switched to v14 before running npm cmds.

**Comment by oscarcuenca** [comment]
Hi
Could you send me a copy of ddbb sql. I will test it in live server
Thanks


________________________________
De: aanachad ***@***.***>
Enviado: martes, 15 de noviembre de 2022 22:32
Para: WailanTirajoh/Laravel-Hotel ***@***.***>
Cc: Oscar Cuenca Roca ***@***.***>; Mention ***@***.***>
Asunto: Re: [WailanTirajoh/Laravel-Hotel] Database connection (Issue #3)


I just installed the repos and it works,
check if you run every command mentionned in readme section, you need also to check your nodejs version.
You can install nvm to switch across multiple versions of npm.
For me I switched to v14 before running npm cmds.

**Comment by WailanTirajoh** [comment]
its might be the local environtment problem, i would suggest you to install https://laragon.org/download.html to get fresh new local server with Laragon and try to clone this project and go through read me installation like @aanachad said.

**Comment by WailanTirajoh** [comment]
[hotel_app.zip](https://github.com/WailanTirajoh/Laravel-Hotel/files/10016413/hotel_app.zip)
@oscarcuenca

**Comment by WailanTirajoh** [comment]
you might want to update your .env to use this sql

APP_KEY=base64:2pZevtAGEWMgyZGwDxW9rLXLaWxmACr17bi1tUWJVng=

**Comment by oscarcuenca** [comment]
Hi
Thans a lot
I test it and later i will keep you informed.
Best Regards
Óscar
________________________________
De: Wailan Tirajoh ***@***.***>
Enviado: martes, 15 de noviembre de 2022 22:48
Para: WailanTirajoh/Laravel-Hotel ***@***.***>
Cc: Oscar Cuenca Roca ***@***.***>; Mention ***@***.***>
Asunto: Re: [WailanTirajoh/Laravel-Hotel] Database connection (Issue #3)


you might want to update your .env to use this sql

APP_KEY=base64:2pZevtAGEWMgyZGwDxW9rLXLaWxmACr17bi1tUWJVng=

**Comment by oscarcuenca** [comment]
Hi firends.
Finally i have gotten it successfully After the DB was created all run ok. The main problem was with xampp. My composer only accepted from 8.0.2 for this project so i had to install xampp 8.0.2 and then light came in. I will try to install Sali for Laravel to avoid in future problems. Thanks,.

**Comment by eneidadelc** [comment]
Hello greetings from Venezuela.
I managed to install the BD without complication. I am using XAMP .
Run MYSQL AND APACHE. Enter the username and password provided by you. And when I press login. 
Help please, where could be the error???

![image](https://user-images.githubusercontent.com/85145715/202916796-9d49cf3b-6786-4fa4-8fb5-3ff2c90023c1.png)
It redirects me to the root directory. It leaves the folder: http://localhost/Laravel-Hotel-main/public/
![image](https://user-images.githubusercontent.com/85145715/202916931-587ad425-31ec-4d98-abe6-82caaf8196b0.png)
