### ISSUE TITLE
Unable to Delete Customer

### ISSUE THREAD

**Issue by RasniNathees** [WailanTirajoh/Laravel-Hotel#47]
Description:
I have encountered an issue where customers cannot be deleted from the system. When attempting to delete a customer, the action fails without any error message or feedback.

Steps to Reproduce:

Go to the customer list page.
Select a customer to delete.
Click the delete button.
Observe that the customer is not removed from the list.
Expected Behavior:
The selected customer should be removed from the list and deleted from the database.

Actual Behavior:
The customer remains on the list and is not deleted.

**Comment by WailanTirajoh** [comment]
Thankyou for the catch and PR
