### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by eneidadelc** [WailanTirajoh/Laravel-Hotel#9]
Hello greetings from Venezuela.

I managed to install the BD without complication. I am using XAMP .

Run MYSQL AND APACHE. Enter the username and password provided by you. And when I press login. 
It redirects me to the root directory.
 It leaves the folder: http://localhost/Laravel-Hotel-main/public/
Help please, where could be the error???
![image](https://user-images.githubusercontent.com/85145715/202917158-a5b9fb4a-68f6-4dfb-a66c-0ef1ea7ea5d0.png)

![image](https://user-images.githubusercontent.com/85145715/202917107-7b1d8d77-077e-4e0a-8680-19a94cfcd42c.png)

**Comment by WailanTirajoh** [comment]
Hi! you might want to setting your vhost for xampp for this.

this might be good reference:
- https://stackoverflow.com/a/27754990/11942385
- https://divpusher.com/blog/how-to-run-laravel-on-windows-with-xampp/

**Comment by WailanTirajoh** [comment]
> Hello greetings from Venezuela.
> 
> I managed to install the BD without complication. I am using XAMP .
> 
> Run MYSQL AND APACHE. Enter the username and password provided by you. And when I press login. It redirects me to the root directory. It leaves the folder: http://localhost/Laravel-Hotel-main/public/ Help please, where could be the error??? ![image](https://user-images.githubusercontent.com/85145715/202917158-a5b9fb4a-68f6-4dfb-a66c-0ef1ea7ea5d0.png)
> 
> ![image](https://user-images.githubusercontent.com/85145715/202917107-7b1d8d77-077e-4e0a-8680-19a94cfcd42c.png)

issue discussed at: https://github.com/WailanTirajoh/Laravel-Hotel/issues/9#issue-1456984945

**Comment by eneidadelc** [comment]
Thank you, @WailanTirajoh 

I tell you what I did

In C:\xampp\apache\conf\extra

 Edit the file: httpd-vhosts and add this code

`<VirtualHost hotel.test:80>
   ServerAdmin hotel.test
   DocumentRoot "C:/xampp/htdocs/Laravel-Hotel-main/public"
   <Directory "C:/xampp/htdocs/Laravel-Hotel-main/public/">
    Require all granted
   </Directory>
</VirtualHost>`

then, in the folder C:\Windows\System32\drivers\etc open the hosts file with notepad and in administrator mode to be able to make modifications, paste the following line and save it.

127.0.0.1  hotel.test

**Comment by WailanTirajoh** [comment]
cool @eneidadelc , can you access it on your browser? http://hotel.test

**Comment by WailanTirajoh** [comment]
cool!

**Comment by datdo06** [comment]
Currently I can only book 1 room for the number of people I fill.
I want to book more than 2 rooms and pay for more than 2 rooms?
